<?php
session_start();
include '../library.php';
if (chkLogin()) {
    header("Location: login.php");
}
?>

<!DOCTYPE HTML>

<html>
	<head>
		<title>Companies</title>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link rel="stylesheet" href="assets/css/main.css" />
		<link rel="stylesheet" type="text/css" href="assets/css/navbar.css">
	</head>
	<body>

		<!-- Header -->
			<header>
				<a class="logo" href=" ">LET'S GET HIRED!</a>
				<nav>
					<ul class="nav__links">
					<li><a href="../index.php">HOME</a></li>
						<li><a href="../dashboard.php">DASHBOARD</a></li>
						<li><a href="../logout.php">LOGOUT</a></li>
					</ul>
				</nav>
				
			</header>

		
		<!-- Banner -->
			<section id="banner">
				<div class="inner">
					<h1><b>List Of Companies</b></h1><br>
					<p>Here is a list of Companies that every tech enthusiast wants to be a part of. Click <a href="#companies"><u>here</u></a> to view these companies and practice some interview questions asked by them.</p>
				</div>
				
			</section>

		<!-- Highlights -->
			<section class="wrapper" id="companies">
				<div class="inner">
					<abc class="special">
						<h2 ><b>These Are some 'A' graded companies</b></h2><br>
						<p>So let's begin the Journey of getting placed in your dream company!</p>
					</abc>
					<div class="highlights">
						<section>
							<div class="content">
								<abc>
									<a href="generic.php#tcs"><img src="images/tcs.jpg"><br><u>Click to Know more</u></a>
								</abc>
								<p>Tata Consultancy Services is an IT services, consulting and business solutions organization that delivers real results to global business, ensuring a level of certainty no other firm can match. TCS offers a consulting-led, integrated portfolio of IT, BPO, infrastructure, engineering and assurance services.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<abc>
									<a href="generic.php#techmahindra"><img src="images/techmahindra.jpg"><br><u>Click to Know more</u></a>
								</abc>
								<p>Tech Mahindra incorporated in 1986 offers Information Technology (IT) services and solution to telecommunications sector across the world. Tech Mahindra is part of the $12.5 billion Mahindra Group, in partnership with British Telecommunications plc (BT), one of the world's leading communications service providers.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<abc>
									<a href="generic.html#cognizant"><img src="images/Cognizant.jpg"><br><u>Click to Know more</u></a>
								</abc>
								<p>Cognizant is an American multinational product led digital corporation that provides digital products, digital IT services, including digital, technology, consulting, and operations services. ... It was founded as an in-house technology unit of Dun & Bradstreet in 1994, and started serving external clients in 1996.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<abc>
									<a href="generic.php#cisco"><img src="images/cisco.jpg"><br><u>Click to Know more</u></a>
								</abc>
								<p>Cisco Systems, Inc. is the world's leading supplier of computer networking products, systems, and services. The company's product line includes routers, switches, remote access devices, protocol translators, Internet services devices, and networking and network management software, all of which link together geographically dispersed local area networks (LANs), wide area networks (WANs), and the Internet itself.</p>
							</div>
						</section>
						
						<section>
							<div class="content">
								<abc>
									<a href="generic.php#wipro"><img src="images/wipro.jpg"><br><u>Click to Know more</u></a>
									
								</abc>
								<p>Wipro Limited is a market leading Information Technology, consulting and business process services company. Wipro utilizes the power of analytics, robotics, cloud and other emerging technologies to help clients spread across six different continents to adapt to the current digital trend and help them thrive to success. Wipro has over 1,60,000 dedicated employees serving together and building a bold and new future. The amount of revenue generated by Wipro in the financial year 2017 is 848 crores USD.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<abc>
									<a href="generic.html#infosys"><img src="images/infosys.jpg"><br><u>Click to Know more</u></a>
								</abc>
								<p>Infosys Limited is an Indian Information Technology company that provides global business consulting and information technology services. Infosys helps clients in 45 countries to create and execute different strategies for their digital transformation. Infosys helps businesses to renew & improve existing conditions so that their business can achieve higher efficiencies and stay relevant according to current times.</p>
							</div>
						</section>
						
					</div>
				</div>
			</section>

		
		
		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>